application: solarpvfree
version: 1
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: css
- url: /(.*\.(gif|png|jpg))$
  static_files: img/\1
  upload: img/.*\.(gif|png|jpg)$
- url: /.*
  script: _go_app
  login: required
